"""Comprehensive Chess Opening Encyclopedia with hierarchical variation themes, purposes, and key plans."""
from typing import Dict, List, Any

OPENING_DATABASE: List[Dict[str, Any]] = [
    # ==========================================
    # 0. FOUNDATIONAL FIRST MOVES (1. e4, 1. d4, 1. e4 e5, 1. d4 d5, 1. d4 Nf6)
    # ==========================================
    {
        "eco": "B00",
        "name": "King's Pawn Opening",
        "name_ko": "킹스 폰 오프닝",
        "moves": ["e4"],
        "defining_move": "1. e4",
        "purpose": "중앙 e4 칸을 즉각 점유하고 퀸과 밝은색 비숍의 공격 사선을 열어 가장 빠르고 공격적인 기물 전개를 도모하는 체스 최고의 클래식 첫 수",
        "white_plan": "Nf3, d4 또는 Bc4로 중앙 지배력을 강화하고 빠른 킹사이드 캐슬링 및 전방 압박",
        "black_plan": "1... e5(오픈 게임), 1... c5(시실리안), 1... e6(프렌치), 1... c6(카로-칸) 등으로 백의 중앙 점유에 맞서 반격 체제 구축",
        "key_ideas": "바비 피셔가 'Best by test(실전으로 검증된 최선)'라고 극찬한 체스 역사상 가장 인기 있는 첫 수",
    },
    {
        "eco": "C20",
        "name": "Open Game (King's Pawn Game)",
        "name_ko": "오픈 게임 (킹스 폰 게임)",
        "moves": ["e4", "e5"],
        "defining_move": "1... e5",
        "purpose": "백의 e4에 1... e5로 정면 맞서 대칭적 중앙 균형을 맞추고, 백의 2. d4 원스텝 중앙 독점을 억제하는 클래시컬 응수",
        "white_plan": "Nf3(나이트 전개 및 e5 공격), Bc4(이탈리안) 또는 Bb5(루이 로페즈)로 주도권 장악",
        "black_plan": "Nc6로 e5를 지키며 비숍과 나이트를 빠르게 전개하여 안정적인 중앙 대등세 유지",
        "key_ideas": "루이 로페즈, 이탈리안 게임, 스카치 게임 등 체스 역사상 가장 유서 깊은 오프닝들의 모태",
    },
    {
        "eco": "A40",
        "name": "Queen's Pawn Opening",
        "name_ko": "퀸스 폰 오프닝",
        "moves": ["d4"],
        "defining_move": "1. d4",
        "purpose": "퀸의 든든한 지원을 받는 d4 칸을 안전하게 점유하고 어두운색 비숍의 활로를 열어 견고하고 전략적인 중앙 장악을 도모하는 첫 수",
        "white_plan": "c4(퀸스 갬빗), Nf3, Nc3를 연계하여 포지셔널한 중앙 영역 우위 및 장기적 압박 구축",
        "black_plan": "1... d5(클로즈드 게임), 1... Nf6(인디언 디펜스) 등으로 백의 e4 중앙 확장을 원천 차단",
        "key_ideas": "1. e4와 함께 체스 이론의 양대 축을 이루는 포지셔널 마스터들의 주무기",
    },
    {
        "eco": "D00",
        "name": "Closed Game (Queen's Pawn Game)",
        "name_ko": "클로즈드 게임 (퀸스 폰 게임)",
        "moves": ["d4", "d5"],
        "defining_move": "1... d5",
        "purpose": "백의 d4에 1... d5로 정면 대응하여 e4 중앙 전진을 차단하고 단단한 폰 센터 균형을 구축하는 수",
        "white_plan": "2. c4(퀸스 갬빗)로 흑의 d5 폰을 흔들거나 2. Bf4(런던 시스템)/2. Nf3로 안정적 배치",
        "black_plan": "e6, c6, Nf6로 견고한 방어선을 구축하고 백의 갬빗을 거절하거나 받아쳐서 반격",
        "key_ideas": "급격한 전술 충돌보다 폰 구조와 기물 배치가 승부를 가르는 깊이 있는 전략 국면",
    },
    {
        "eco": "A45",
        "name": "Indian Defense",
        "name_ko": "인디언 디펜스",
        "moves": ["d4", "Nf6"],
        "defining_move": "1... Nf6",
        "purpose": "나이트를 즉시 전개하여 백의 2. e4 중앙 폰 구축을 차단하고, 흑의 선택에 따라 킹스 인디언, 님조 인디언, 그륀펠트 등으로 유연하게 전환하는 현대 체스의 핵심 무기",
        "white_plan": "2. c4 후 Nc3, e4로 넓은 중앙 폰 센터를 장악하려는 정석적 확장",
        "black_plan": "g6(KID/그륀펠트), e6(님조/QID), c5(베노니) 등 유연한 하이퍼모던 카운터 셋업",
        "key_ideas": "중앙을 폰으로 서둘러 고정하지 않고 기물로 유연하게 제어하는 현대 체스 이론의 정점",
    },

    # ==========================================
    # 1. KING'S PAWN OPENING (1. e4) - SICILIAN DEFENSE
    # ==========================================
    {
        "eco": "B20",
        "name": "Sicilian Defense",
        "name_ko": "시실리안 디펜스",
        "moves": ["e4", "c5"],
        "defining_move": "1... c5",
        "purpose": "비대칭적인 c5 전진으로 백의 이상적인 d4 중앙 폰 차지를 견제하고, c-열을 개방하여 날카로운 퀸사이드 역습을 전개하는 것",
        "white_plan": "Nf3 후 d4 중앙 폰 브레이크로 공격 사선을 열고 빠른 기물 전개 및 킹사이드 공세",
        "black_plan": "c-오픈 파일을 통한 퀸사이드 압박 및 중앙 폰 우위(d/e 폰)를 바탕으로 한 카운터어택",
        "key_ideas": "체스 역사상 흑에게 가장 공격적이고 승률이 높은 비대칭 카운터 오프닝",
    },
    {
        "eco": "B22",
        "name": "Sicilian Defense: Alapin Variation",
        "name_ko": "시실리안 디펜스: 알라핀 바리에이션",
        "moves": ["e4", "c5", "c3"],
        "defining_move": "2. c3",
        "purpose": "c3를 미리 두어 흑이 cxd4로 잡더라도 c폰으로 되잡아 d4에 단단한 중앙 폰 쐐기를 유지하려는 수",
        "white_plan": "d4를 성공시켜 견고한 폰 센터를 구축하고 안정적인 미들게임 운영",
        "black_plan": "2... d5 또는 2... Nf6로 백의 d4 구축 전에 중앙을 즉각 타격",
        "key_ideas": "오픈 시실리안의 복잡한 난타전을 피하고 포지셔널한 우위를 꾀하는 백의 실용적 무기",
    },
    {
        "eco": "B23",
        "name": "Sicilian Defense: Closed Sicilian",
        "name_ko": "시실리안 디펜스: 클로즈드 시실리안",
        "moves": ["e4", "c5", "Nc3"],
        "defining_move": "2. Nc3",
        "purpose": "d4 중앙 개방을 서두르지 않고 g3-Bg2 피앙케토를 통해 닫힌 국면에서 킹사이드 공격을 준비하는 수",
        "white_plan": "g3, Bg2, d3, f4로 킹사이드 폰 스톰을 감행",
        "black_plan": "g6, Bg7, Rb8, b5로 퀸사이드 공간을 빠르게 확장하며 반격",
        "key_ideas": "포지셔널하면서도 양측 날개 공격(Flank Attack)이 충돌하는 전략적 국면",
    },
    {
        "eco": "B27",
        "name": "Sicilian Defense: Open Sicilian",
        "name_ko": "시실리안 디펜스: 오픈 시실리안",
        "moves": ["e4", "c5", "Nf3"],
        "defining_move": "2. Nf3",
        "purpose": "d4 중앙 개방을 가장 신속하고 강력하게 준비하는 오픈 시실리안의 메인 게이트웨이",
        "white_plan": "3. d4 cxd4 4. Nxd4로 중앙을 열고 기물 전개 속도 우위 확보",
        "black_plan": "2... d6, 2... Nc6, 2... e6 중 원하는 바리에이션을 선택하여 반격 체제 구축",
        "key_ideas": "현대 체스에서 가장 이론이 깊고 날카로운 전술 공방의 출발점",
    },
    {
        "eco": "B50",
        "name": "Sicilian Defense: d6 Line",
        "name_ko": "시실리안 디펜스: d6 정석",
        "moves": ["e4", "c5", "Nf3", "d6"],
        "defining_move": "2... d6",
        "purpose": "e5 칸을 통제하고 c8 비숍의 길을 열며 나이돌프, 드래곤, 클래시컬 등 메이저 바리에이션으로의 진입을 준비하는 수",
        "white_plan": "3. d4 cxd4 4. Nxd4 Nf6 5. Nc3로 강력한 중앙 기물 배치",
        "black_plan": "5... a6(나이돌프) 또는 5... g6(드래곤), 5... e6(셰베닝겐)으로 분기하여 카운터어택",
        "key_ideas": "세계 최고 수준의 마스터들이 가장 선호하는 시실리안의 절대 메인스트림",
    },
    {
        "eco": "B30",
        "name": "Sicilian Defense: Old Sicilian",
        "name_ko": "시실리안 디펜스: 올드 시실리안",
        "moves": ["e4", "c5", "Nf3", "Nc6"],
        "defining_move": "2... Nc6",
        "purpose": "나이트를 먼저 c6로 전개하여 d4와 e5 중앙 칸을 직접 압박하는 클래시컬 시실리안 셋업",
        "white_plan": "3. d4 cxd4 4. Nxd4로 오픈 시실리안을 두거나 3. Bb5(로솔리모 바리에이션)로 압박",
        "black_plan": "4... Nf6 5. Nc3 e5(스베시니코프) 또는 4... g6(액셀러레이티드 드래곤)으로 전개",
        "key_ideas": "스베시니코프와 액셀러레이티드 드래곤의 출발점이 되는 유연한 전개",
    },
    {
        "eco": "B40",
        "name": "Sicilian Defense: French Variation",
        "name_ko": "시실리안 디펜스: 프렌치 바리에이션",
        "moves": ["e4", "c5", "Nf3", "e6"],
        "defining_move": "2... e6",
        "purpose": "e6로 d5 브레이크를 준비하고 어두운색 비숍의 전개 사선을 확보하는 폴센/타이마노프 셋업",
        "white_plan": "3. d4 cxd4 4. Nxd4로 중앙을 개방하거나 3. c3/3. g3로 유연 대응",
        "black_plan": "4... a6(카나 바리에이션) 또는 4... Nc6(타이마노프 바리에이션)으로 퀸사이드 주도권 장악",
        "key_ideas": "견고한 폰 구조와 유연한 기물 전개를 결합한 포지셔널 시실리안",
    },
    {
        "eco": "B56",
        "name": "Sicilian Defense: Classical Variation",
        "name_ko": "시실리안 디펜스: 클래시컬 바리에이션",
        "moves": ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "Nc6"],
        "defining_move": "5... Nc6",
        "purpose": "양측 나이트를 모두 중앙으로 전개하여 가장 정석적이고 견고한 피스 플레이를 펼치는 고전 바리에이션",
        "white_plan": "6. Bg5(리히터-라우저 어택)로 흑 진영을 압박하거나 6. Bc4(소진 어택)로 f7을 조준",
        "black_plan": "e6, Be7, O-O 후 a6, Qc7, Bd7로 균형 잡힌 기물 조율",
        "key_ideas": "현대 전술 이론의 토대가 된 정통 시실리안의 명작",
    },
    {
        "eco": "B90",
        "name": "Sicilian Defense: Najdorf Variation",
        "name_ko": "시실리안 디펜스: 나이돌프 바리에이션",
        "moves": ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "a6"],
        "defining_move": "5... a6",
        "purpose": "백의 Nb5 침투 및 Bb5+ 체크를 원천 차단하고 향후 ...b5 폰 확장을 준비하는 유연성의 극치",
        "white_plan": "Be3, f3, Qd2, O-O-O로 긴 캐슬링 후 g4-h4 폰 스톰을 퍼붓는 잉글리시 어택(English Attack) 또는 6. Bg5 공격",
        "black_plan": "b5 전진, Bb7 배치, Rc8과 Nc4를 통한 퀸사이드 다이렉트 침투 및 카운터어택",
        "key_ideas": "바비 피셔와 가리 카스파로프의 주무기로 역사상 가장 완성도 높고 날카로운 오프닝 라인",
    },
    {
        "eco": "B70",
        "name": "Sicilian Defense: Dragon Variation",
        "name_ko": "시실리안 디펜스: 드래곤 바리에이션",
        "moves": ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "g6"],
        "defining_move": "5... g6",
        "purpose": "다크 스퀘어 비숍을 g7에 피앙케토(Fianchetto)하여 h8-a1 긴 대각선과 d4/c3 기점을 정밀 타격하는 것",
        "white_plan": "유고슬라브 어택(Be3, f3, Qd2, O-O-O, Bh6, h4-h5)으로 흑 킹을 직격",
        "black_plan": "c-열 룩과 Nc5/Ne5, b5 확장을 통해 백의 퀸사이드를 먼저 파괴",
        "key_ideas": "한 템포 차이로 승부가 갈리는 체스 역사상 가장 극적인 체크메이트 스피드 레이스",
    },
    {
        "eco": "B80",
        "name": "Sicilian Defense: Scheveningen Variation",
        "name_ko": "시실리안 디펜스: 셰베닝겐 바리에이션",
        "moves": ["e4", "c5", "Nf3", "d6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e6"],
        "defining_move": "5... e6",
        "purpose": "d6-e6의 견고한 '스몰 센터(Small Center)'를 구축하여 백의 중앙 침투를 탄력적으로 방어하는 라인",
        "white_plan": "케레스 어택(6. g4) 또는 f4 전진을 통한 킹사이드 압박",
        "black_plan": "Be7, O-O, a6, Qc7 후 d5 중앙 브레이크로 반격",
        "key_ideas": "클래식한 탄력성을 바탕으로 한 폰 센터 방어와 날카로운 중앙 돌파의 조화",
    },
    {
        "eco": "B33",
        "name": "Sicilian Defense: Sveshnikov Variation",
        "name_ko": "시실리안 디펜스: 스베시니코프 바리에이션",
        "moves": ["e4", "c5", "Nf3", "Nc6", "d4", "cxd4", "Nxd4", "Nf6", "Nc3", "e5"],
        "defining_move": "5... e5",
        "purpose": "d5 칸과 d6 폰 약점을 내주는 대신, 백 나이트를 외곽(a3)으로 쫓아내고 폭발적인 기물 활동성을 얻는 것",
        "white_plan": "Nd5 전초기지를 장악하고 c4(마로치 바인드 형태)로 흑의 d5 브레이크를 영구 억제",
        "black_plan": "f5 폰 전진을 통한 킹사이드 다이내믹 반격 및 활발한 비숍 기동",
        "key_ideas": "매그너스 칼슨이 세계 챔피언십에서 애용한 현대 다이내믹 체스의 걸작",
    },

    # ==========================================
    # 2. KING'S PAWN OPENING (1. e4 e5) - RUY LOPEZ & ITALIAN
    # ==========================================
    {
        "eco": "C60",
        "name": "Ruy Lopez (Spanish Opening)",
        "name_ko": "루이 로페즈 (스패니시 오프닝)",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bb5"],
        "defining_move": "3. Bb5",
        "purpose": "e5 폰을 지키는 흑의 c6 나이트를 간접 압박(Pin)하여 중앙 주도권을 쥐려는 체스 최고의 고전 정석",
        "white_plan": "빠른 O-O 캐슬링 후 c3-d4로 중앙 지배력 구축 및 Re1을 통한 e-파일 지배",
        "black_plan": "3... a6(모피 디펜스)로 비숍을 물러서게 하거나 3... Nf6(베를린)로 e4를 역공",
        "key_ideas": "체스 오프닝 중 가장 깊은 전략 이론과 포지셔널한 아름다움을 지닌 정석",
    },
    {
        "eco": "C65",
        "name": "Ruy Lopez: Berlin Defense",
        "name_ko": "루이 로페즈: 베를린 디펜스",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bb5", "Nf6"],
        "defining_move": "3... Nf6",
        "purpose": "흑이 e5 폰을 지키지 않고 3... Nf6로 백의 e4를 즉각 역공하며, 가장 견고하고 뚫리지 않는 '베를린 장벽'을 구축하는 것",
        "white_plan": "4. O-O Nxe4 5. d4 Nd6 6. Bxc6 dxc6 7. dxe5 Nf5 8. Qxd8+ Kxd8로 퀸 교환 엔드게임(Berlin Wall Endgame) 진입",
        "black_plan": "더블폰과 캐슬링 권한 상실을 감수하는 대신, 강력한 비숍 쌍(Bishop Pair)으로 난공불락의 수비 구축",
        "key_ideas": "블라디미르 크람닉이 카스파로프를 무너뜨릴 때 사용한 현대 최고 수준의 철벽 엔드게임 정석",
    },
    {
        "eco": "C78",
        "name": "Ruy Lopez: Morphy Defense",
        "name_ko": "루이 로페즈: 모피 디펜스",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6"],
        "defining_move": "3... a6",
        "purpose": "백 비숍에게 질문(Question the Bishop)을 던져 a4로 물러서게 만들고 향후 ...b5 확장을 준비하는 가장 대중적인 메인 라인",
        "white_plan": "4. Ba4 Nf6 5. O-O Be7 6. Re1 b5 7. Bb3 d6 8. c3 O-O 9. h3로 탄탄한 중앙 구축",
        "black_plan": "b5 확장 후 Na5(치고린) 또는 Nb8-d7(브레예르)로 나이트를 재배치하며 중앙 균형 유지",
        "key_ideas": "세계 챔피언십에서 가장 많이 등장한 클래시컬 루이 로페즈의 표준",
    },
    {
        "eco": "C50",
        "name": "Italian Game",
        "name_ko": "이탈리안 게임",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4"],
        "defining_move": "3. Bc4",
        "purpose": "흑 진영에서 가장 취약한 f7 폰을 직접 조준하며 빠른 기물 전개와 킹사이드 캐슬링을 준비하는 클래식 오프닝",
        "white_plan": "c3 후 d4로 중앙을 장악하거나, d3(Giuoco Pianissimo)로 조용하고 단단하게 기물을 조율",
        "black_plan": "3... Bc5(지우오코 피아노)로 맞불을 놓거나 3... Nf6(투 나이츠 디펜스)로 e4를 적극 역공",
        "key_ideas": "초보자부터 엘리트 그랜드마스터까지 전 세대에 걸쳐 사랑받는 클래식 오프닝",
    },
    {
        "eco": "C55",
        "name": "Two Knights Defense",
        "name_ko": "투 나이츠 디펜스",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6"],
        "defining_move": "3... Nf6",
        "purpose": "f7 폰의 취약함을 두려워하지 않고 백의 e4 중앙 폰을 즉각 역공하여 주도권을 빼앗으려는 흑의 가장 공격적인 카운터 오프닝",
        "white_plan": "4. Ng5로 f7을 즉시 2중 공격(나이트 어택/프라이드 리버)하거나, 4. d3로 차분하게 기물을 전개",
        "black_plan": "백의 4. Ng5에 4... d5 5. exd5 Na5!로 폰을 일시 희생하더라도 백 비숍을 쫓아내며 막강한 전개 속도와 공격 사선 장악",
        "key_ideas": "수비에 머물지 않고 즉각적인 맞불 공격을 가하는 다이내믹 이탈리안의 대표 라인",
    },
    {
        "eco": "C57",
        "name": "Two Knights Defense: Knight Attack",
        "name_ko": "투 나이츠 디펜스: 나이트 어택",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5"],
        "defining_move": "4. Ng5",
        "purpose": "비숍과 나이트를 f7 지점에 집중시켜 흑에게 치명적인 포크 및 기물 손실 위협을 가하는 백의 극단적 공격수",
        "white_plan": "4... d5 5. exd5 후 흑이 5... Nxd5로 받으면 6. Nxf7!(프라이드 리버)로 킹을 파괴",
        "black_plan": "5... Na5 6. Bb5+ c6 7. dxc6 bxc6로 폰을 내주고 퀸사이드와 중앙에서 강력한 기물 주도권 행사",
        "key_ideas": "오프닝 초반 가장 치열하고 날카로운 전술 난타전의 기점",
    },
    {
        "eco": "C50",
        "name": "Italian Game: Giuoco Piano",
        "name_ko": "이탈리안 게임: 지우오코 피아노",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5"],
        "defining_move": "3... Bc5",
        "purpose": "대칭적으로 비숍을 c5에 전개하여 백의 f2 폰을 견제하고 탄탄한 중앙 균형을 맞추는 클래시컬 이탈리안 정석",
        "white_plan": "c3 후 d4로 중앙을 타격하거나, d3(Giuoco Pianissimo)로 조용하고 단단하게 기물을 조율",
        "black_plan": "Nf6, d6, O-O로 안전하게 캐슬링을 마치고 백의 d4 돌파를 안정적으로 저지",
        "key_ideas": "체스 오프닝의 가장 클래식한 기물 배치와 균형미를 보여주는 정통 라인",
    },
    {
        "eco": "C51",
        "name": "Evans Gambit",
        "name_ko": "에반스 갬빗",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "b4"],
        "defining_move": "4. b4",
        "purpose": "b4 폰을 희생하여 흑 비숍을 유인하고, c3-d4로 템포를 벌며 폭풍 같은 중앙 폰 센터와 강력한 공격 사선을 구축하는 낭만주의 갬빗",
        "white_plan": "4... Bxb4 5. c3 Ba5 6. d4로 중앙을 완전히 장악하고 흑 킹을 향해 전방위 공세",
        "black_plan": "5... Be7 또는 5... Ba5로 침착하게 비숍을 후퇴시키고 폰 우위를 지키며 수비선 구축",
        "key_ideas": "카스파로프가 극찬한 '체스 역사상 가장 아름다운 갬빗 오프닝'",
    },
    {
        "eco": "C53",
        "name": "Italian Game: Giuoco Pianissimo",
        "name_ko": "이탈리안 게임: 지우오코 피아니시모",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Bc5", "c3", "Nf6", "d3"],
        "defining_move": "4. c3 / 5. d3",
        "purpose": "'가장 조용한 게임'이라는 뜻으로, 급격한 전술 충돌을 피하고 폰 구조를 단단히 잠근 채 기물 기동에 집중하는 수",
        "white_plan": "Nbd2-f1-g3 기물 재배치 및 a4 공간 확장 후 때를 보아 d4 돌파",
        "black_plan": "a6, Ba7로 비숍을 안전하게 뒤로 빼고 d6, O-O 후 중앙 및 킹사이드 수비",
        "key_ideas": "현대 슈퍼 토너먼트에서 가장 빈번하게 채택되는 포지셔널 이탈리안의 정점",
    },
    {
        "eco": "C57",
        "name": "Two Knights Defense: Fried Liver Attack",
        "name_ko": "투 나이츠 디펜스: 프라이드 리버 어택",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Bc4", "Nf6", "Ng5", "d5", "exd5", "Nxd5", "Nxf7"],
        "defining_move": "6. Nxf7",
        "purpose": "f7 지점에 나이트를 희생하여 흑 킹을 중앙으로 끌어내고 치명적인 핀과 집중 공격을 퍼붓는 전술적 갬빗",
        "white_plan": "7. Qf3+ Ke6 8. Nc3로 d5에 고정된 흑 나이트를 3중 압박하여 킹을 포위",
        "black_plan": "킹을 위험에 노출시키면서도 침착하게 기물들을 d5 수비에 결집하여 기물 우위 지키기",
        "key_ideas": "체스 전술의 백미로 꼽히는 전설적인 공격 갬빗 라인",
    },
    {
        "eco": "C45",
        "name": "Scotch Game",
        "name_ko": "스카치 게임",
        "moves": ["e4", "e5", "Nf3", "Nc6", "d4"],
        "defining_move": "3. d4",
        "purpose": "3수만에 중앙 d4를 즉각 개방하여 흑의 e5 폰을 제거하고 빠른 기물 기동력과 공격 사선을 확보하려는 수",
        "white_plan": "3... exd4 4. Nxd4로 중앙 나이트 우위를 점하고 Bc4, Nc3로 빠른 전개 및 킹사이드 공세",
        "black_plan": "4... Bc5 또는 4... Nf6로 백의 d4 나이트를 즉각 타격하며 대등한 카운터 전개",
        "key_ideas": "가리 카스파로프가 세계 챔피언십에서 부활시킨 강력한 오픈 게임 무기",
    },
    {
        "eco": "C30",
        "name": "King's Gambit",
        "name_ko": "킹스 갬빗",
        "moves": ["e4", "e5", "f4"],
        "defining_move": "2. f4",
        "purpose": "2수만에 f4 폰을 희생하여 흑의 e5 중앙 폰을 유인해 내고, d4 중앙 독점과 f-열 개방을 통해 흑 킹을 맹폭하는 낭만주의 오프닝",
        "white_plan": "Nf3, Bc4, d4, O-O 후 f-열 룩과 기물들의 압도적 공격력으로 f7 지점 강습",
        "black_plan": "2... exf4(수락) 후 d5 또는 g5로 폰을 지키거나 2... d5(팔크베어 갬빗)로 중앙 역공",
        "key_ideas": "체스 역사상 가장 공격적이고 로맨틱한 고전 명작 오프닝",
    },
    {
        "eco": "C47",
        "name": "Four Knights Game",
        "name_ko": "포 나이츠 게임",
        "moves": ["e4", "e5", "Nf3", "Nc6", "Nc3", "Nf6"],
        "defining_move": "3... Nf6 (with 3. Nc3)",
        "purpose": "양측이 4개의 나이트를 모두 중앙으로 전개하여 대칭적이고 견고한 기초 전개를 마치는 안정적 오프닝",
        "white_plan": "4. Bb5(스패니시 바리에이션) 또는 4. d4(스카치 바리에이션)로 중앙 개방",
        "black_plan": "4... Bb4로 대칭 맞불을 놓거나 Nd4로 백 진영을 교란하며 안정적 무승부 및 균형 지향",
        "key_ideas": "기물 전개의 기본 원칙을 가장 충실히 따르는 교과서적 오프닝",
    },

    # ==========================================
    # 3. KING'S PAWN OPENING (1. e4) - FRENCH & CARO-KANN & SCANDINAVIAN
    # ==========================================
    {
        "eco": "C00",
        "name": "French Defense",
        "name_ko": "프렌치 디펜스",
        "moves": ["e4", "e6"],
        "defining_move": "1... e6",
        "purpose": "2... d5 전진을 준비하여 중앙을 단단히 방어하고, 백의 e4 폰에 즉각적인 구조적 압박을 가하는 수",
        "white_plan": "2. d4 d5 3. e5(Advance)로 공간을 잠그거나 3. Nc3/Nd2로 중앙 텐션 유지",
        "black_plan": "c5 중앙 폰 브레이크 및 Qb6, Nc6로 백의 d4 폰 베이스를 집중 공격",
        "key_ideas": "c8 '프렌치 비숍'의 답답함을 극복하고 백의 폰 체인을 부수는 카운터 전략",
    },
    {
        "eco": "C02",
        "name": "French Defense: Advance Variation",
        "name_ko": "프렌치 디펜스: 어드밴스 바리에이션",
        "moves": ["e4", "e6", "d4", "d5", "e5"],
        "defining_move": "3. e5",
        "purpose": "e5로 폰을 전진시켜 흑의 Nf6 전개를 차단하고 킹사이드 공간 우위를 영구 확보하려는 수",
        "white_plan": "c3로 d4를 지키고 Nf3, Bd3, O-O 후 킹사이드 공격 전개",
        "black_plan": "즉각적인 3... c5 폰 브레이크 후 Nc6, Qb6, Nh6-f5로 d4 폰을 전방위 타격",
        "key_ideas": "폰 체인의 정면 충돌과 기지(Base) 파괴를 둘러싼 클래식한 전략 대결",
    },
    {
        "eco": "C15",
        "name": "French Defense: Winawer Variation",
        "name_ko": "프렌치 디펜스: 위나워 바리에이션",
        "moves": ["e4", "e6", "d4", "d5", "Nc3", "Bb4"],
        "defining_move": "3... Bb4",
        "purpose": "c3 나이트를 핀(Pin)하여 e4 폰을 강하게 압박하고 필요 시 나이트를 잡아 백에게 더블폰을 강요하는 가장 날카로운 프렌치 라인",
        "white_plan": "4. e5 c5 5. a3 Bxc3+ 6. bxc3 Ne7 7. Qg4로 흑의 취약한 g7 지점을 공습",
        "black_plan": "7... Qc7 또는 7... O-O 후 c4/Qa5로 백의 퀸사이드 더블폰과 약점을 파괴",
        "key_ideas": "백의 비숍 페어와 킹사이드 공격력 vs 흑의 완벽한 폰 구조와 퀸사이드 카운터",
    },
    {
        "eco": "C03",
        "name": "French Defense: Tarrasch Variation",
        "name_ko": "프렌치 디펜스: 타라시 바리에이션",
        "moves": ["e4", "e6", "d4", "d5", "Nd2"],
        "defining_move": "3. Nd2",
        "purpose": "3... Bb4 핀을 방지하고 c3 전진을 가능하게 하여 중앙 폰 구조를 견고하게 유지하려는 아나톨리 카르포프의 주무기",
        "white_plan": "Ngf3, Bd3, c3, O-O로 안정적인 전개 후 중앙 주도권 행사",
        "black_plan": "3... c5(오픈 타라시) 또는 3... Nf6로 백의 d4/e4 센터를 즉각 시험",
        "key_ideas": "안정적이고 포지셔널한 우위를 추구하는 백의 테크니컬 시스템",
    },
    {
        "eco": "B10",
        "name": "Caro-Kann Defense",
        "name_ko": "카로-칸 디펜스",
        "moves": ["e4", "c6"],
        "defining_move": "1... c6",
        "purpose": "c8 비숍의 대각선을 막지 않으면서 안전하게 2... d5 중앙 폰 지지대를 마련하는 가장 견고한 수비 오프닝",
        "white_plan": "2. d4 d5 후 3. Nc3(Classical) 또는 3. e5(Advance)로 공간 확보",
        "black_plan": "Bf5 또는 Bg4로 라이트 스퀘어 비숍을 먼저 폰 체인 밖으로 전개한 뒤 e6 구축",
        "key_ideas": "아나톨리 카르포프가 애용한 체스에서 가장 단단하고 약점이 적은 방패",
    },
    {
        "eco": "B12",
        "name": "Caro-Kann Defense: Advance Variation",
        "name_ko": "카로-칸 디펜스: 어드밴스 바리에이션",
        "moves": ["e4", "c6", "d4", "d5", "e5"],
        "defining_move": "3. e5",
        "purpose": "중앙 공간을 선점하여 흑의 기동성을 제한하려는 백의 가장 공격적인 대응",
        "white_plan": "h4(탈 어택) 또는 Nf3-Be2로 흑의 Bf5 비숍을 압박하고 공간 우위 활용",
        "black_plan": "3... Bf5로 비숍을 안전하게 꺼낸 뒤 e6, c5로 백의 d4 중앙을 허물기",
        "key_ideas": "흑의 Bf5 비숍 생존 여부와 백의 폰 체인 유지력이 승부를 가르는 메인 배틀그라운드",
    },
    {
        "eco": "B18",
        "name": "Caro-Kann Defense: Classical (Capablanca)",
        "name_ko": "카로-칸 디펜스: 카포블랑카 바리에이션",
        "moves": ["e4", "c6", "d4", "d5", "Nc3", "dxe4", "Nxe4", "Bf5"],
        "defining_move": "4... Bf5",
        "purpose": "중앙 폰을 교환하고 라이트 비숍을 폰 체인 밖으로 완벽히 꺼내어 견고함의 극치를 달성하는 호세 카포블랑카의 정석",
        "white_plan": "Ng3 Bg6 6. h4 h6 7. Nf3 Nd7 8. h5 Bh7 9. Bd3로 비숍을 교환하고 킹사이드 공간 우위 모색",
        "black_plan": "e6, Ngf6, Be7, O-O 후 c5로 백의 중앙을 분쇄하며 완벽한 엔드게임 지향",
        "key_ideas": "체스에서 가장 약점이 적고 무결점의 폰 구조를 자랑하는 클래식",
    },
    {
        "eco": "B01",
        "name": "Scandinavian Defense",
        "name_ko": "스칸디나비안 디펜스",
        "moves": ["e4", "d5"],
        "defining_move": "1... d5",
        "purpose": "1수부터 백의 e4 폰을 직접 타격하여 즉각적인 중앙 개방과 빠른 기물 자유도를 얻으려는 수",
        "white_plan": "2. exd5 Qxd5 3. Nc3로 흑 퀸을 쫓아내며 템포 우위를 쥐고 d4 장악",
        "black_plan": "3... Qa5(또는 Qd6, Qd8)로 퀸을 안전하게 배치한 후 c6, Bf5, Nf6로 견고한 진형 구성",
        "key_ideas": "초반 템포를 내주는 대신 빠르고 명확한 기물 전개 라인을 확보하는 실전형 오프닝",
    },
    {
        "eco": "B07",
        "name": "Pirc Defense",
        "name_ko": "피르츠 디펜스",
        "moves": ["e4", "d6", "d4", "Nf6", "Nc3", "g6"],
        "defining_move": "3... g6",
        "purpose": "중앙을 직접 점유하지 않고 g7 비숍 피앙케토와 ...c6, ...e5 카운터를 노리는 하이퍼모던 1. e4 대응책",
        "white_plan": "f4(오스트리안 어택) 또는 Be3, Qd2(150 어택)로 킹사이드 맹공 감행",
        "black_plan": "c6, b5 확장 또는 e5 중앙 브레이크로 백의 센터를 측면에서 붕괴",
        "key_ideas": "비대칭적이고 유연한 전개로 백의 중앙을 역습하는 다이내믹 수비",
    },
    {
        "eco": "B02",
        "name": "Alekhine's Defense",
        "name_ko": "알레킨 디펜스",
        "moves": ["e4", "Nf6"],
        "defining_move": "1... Nf6",
        "purpose": "1수부터 나이트로 e4를 도발하여 백 폰들의 전진을 유도하고, 과도하게 전진된 백의 폰 센터를 카운터 타격하는 알렉산더 알레킨의 혁신적 오프닝",
        "white_plan": "2. e5 Nd5 3. d4 d6 4. c4 Nb6 5. f4(Four Pawns Attack)로 거대한 센터 구축",
        "black_plan": "dxe5, Nc6, Bg4, g6로 백의 폰들을 집중 사격하여 전진 폰 구조를 붕괴",
        "key_ideas": "폰을 전진하도록 유혹하여 약점으로 만들어내는 하이퍼모던의 진수",
    },

    # ==========================================
    # 4. QUEEN'S PAWN OPENING (1. d4) - QUEEN'S GAMBIT & SLAV
    # ==========================================
    {
        "eco": "D06",
        "name": "Queen's Gambit",
        "name_ko": "퀸즈 갬빗",
        "moves": ["d4", "d5", "c4"],
        "defining_move": "2. c4",
        "purpose": "c4 날개 폰을 희생 제안하여 흑의 d5 중앙 폰을 유인해 내고, e4 전진을 통해 완벽한 중앙(d4+e4)을 장악하려는 전략",
        "white_plan": "cxd5 교환 후 Nc3, e4, Nf3로 중앙 지배 및 퀸사이드 압박",
        "black_plan": "2... e6(QGD)나 2... c6(Slav)로 폰을 지키거나, 2... dxc4(QGA)로 받아먹고 반격",
        "key_ideas": "체스 역사상 가장 위대하고 완벽한 1. d4 오프닝 시스템",
    },
    {
        "eco": "D20",
        "name": "Queen's Gambit Accepted (QGA)",
        "name_ko": "퀸즈 갬빗 수락",
        "moves": ["d4", "d5", "c4", "dxc4"],
        "defining_move": "2... dxc4",
        "purpose": "c4 폰을 일시적으로 잡아서 중앙 텐션을 해소하고, 빠른 ...c5 및 ...a6, ...b5 전개로 퀸사이드 반격을 노리는 수",
        "white_plan": "e4 또는 e3 후 Bxc4로 폰을 무난히 회수하고 강력한 중앙 지배력 행사",
        "black_plan": "c4 폰을 무리하게 지키지 않고, Nf6, e6, c5로 백의 d4 센터를 즉각 타격",
        "key_ideas": "깔끔하고 오픈된 기물 전개를 선호하는 플레이어들의 실용적 선택",
    },
    {
        "eco": "D30",
        "name": "Queen's Gambit Declined (QGD)",
        "name_ko": "퀸즈 갬빗 거절",
        "moves": ["d4", "d5", "c4", "e6"],
        "defining_move": "2... e6",
        "purpose": "e6로 d5 폰을 굳건히 지탱하여 백에게 중앙을 절대 내주지 않는 가장 클래식하고 견고한 방어",
        "white_plan": "Nc3, Nf3, Bg5로 흑의 f6 나이트를 핀(Pin)하고 e3, Bd3 후 중앙 압박",
        "black_plan": "Nf6, Be7, O-O 후 c6 또는 c5로 카운터 및 c8 비숍의 활로 모색",
        "key_ideas": "카스파로프, 카르포프 등 역대 모든 세계 챔피언들이 검증한 불멸의 방패",
    },
    {
        "eco": "D10",
        "name": "Slav Defense",
        "name_ko": "슬라브 디펜스",
        "moves": ["d4", "d5", "c4", "c6"],
        "defining_move": "2... c6",
        "purpose": "c8 비숍의 대각선을 막지 않으면서 c6 폰으로 d5를 견고하게 지키는 현대 엘리트 체스의 최고 인기 정석",
        "white_plan": "Nf3, Nc3 후 e3 또는 cxd5 교환으로 중앙 주도권 유지",
        "black_plan": "Bf5(또는 Bg4)로 비숍을 먼저 꺼낸 후 e6, Nbd7, dxc4로 기물 활동성 극대화",
        "key_ideas": "QGD의 견고함과 카로칸의 비숍 자유도를 결합한 완벽한 폰 구조",
    },
    {
        "eco": "D43",
        "name": "Semi-Slav Defense",
        "name_ko": "세미-슬라브 디펜스",
        "moves": ["d4", "d5", "c4", "c6", "Nf3", "Nf6", "Nc3", "e6"],
        "defining_move": "4... e6",
        "purpose": "c6와 e6 양쪽으로 d5를 철벽 방어(트라이앵글 셋업)하면서 dxc4 후 ...b5 확장을 노리는 초고난도 엘리트 정석",
        "white_plan": "5. Bg5(보트비닉/모스크바)로 극도의 전술전을 펼치거나 5. e3(메라노)로 안정적 전개",
        "black_plan": "dxc4, b5, a6, c5(메라노 바리에이션)로 퀸사이드 폰 다수를 만들며 반격",
        "key_ideas": "아난드, 크람닉 등 현대 챔피언십에서 가장 치열하게 격돌한 명품 오프닝",
    },
    {
        "eco": "D02",
        "name": "London System",
        "name_ko": "런던 시스템",
        "moves": ["d4", "d5", "Nf3", "Nf6", "Bf4"],
        "defining_move": "3. Bf4 (또는 2. Bf4)",
        "purpose": "e3를 두기 전에 c1 다크 스퀘어 비숍을 f4로 먼저 전개하여 완벽한 '피라미드 폰 센터(c3-d4-e3)'를 구축하는 만능 시스템",
        "white_plan": "e3, Bd3, Nbd2, c3, Ne5 후 킹사이드 기물 집중 공격 및 안정적인 진형 유지",
        "black_plan": "c5, Qb6로 백의 b2/d4를 찌르거나, Bd6로 f4 비숍을 맞교환하여 무력화",
        "key_ideas": "흑의 어떤 대응에도 흔들리지 않고 일관된 고품질 포지션을 보장하는 현대 최고의 인기 시스템",
    },

    # ==========================================
    # 5. INDIAN DEFENSES (1. d4 Nf6) - KID, NIMZO, GRUNFELD
    # ==========================================
    {
        "eco": "E60",
        "name": "King's Indian Defense",
        "name_ko": "킹스 인디언 디펜스 (KID)",
        "moves": ["d4", "Nf6", "c4", "g6"],
        "defining_move": "2... g6",
        "purpose": "백에게 거대한 중앙 폰 센터(d4+c4+e4)를 의도적으로 내어준 뒤, Bg7 피앙케토와 ...e5/...f5 폰 폭풍으로 킹사이드를 초토화시키는 하이퍼모던 카운터 오프닝",
        "white_plan": "Nc3, e4, d5(클래시컬)로 중앙을 잠그고 퀸사이드(c5 브레이크)에서 흑 진영을 침공",
        "black_plan": "d6, O-O, e5, Ne7/Nh5 후 f5-f4로 백 킹을 향해 올인성 다이렉트 킹사이드 공격",
        "key_ideas": "바비 피셔와 가리 카스파로프의 심장이자 체스에서 가장 불꽃 튀는 공격적 오프닝",
    },
    {
        "eco": "E20",
        "name": "Nimzo-Indian Defense",
        "name_ko": "님조-인디언 디펜스",
        "moves": ["d4", "Nf6", "c4", "e6", "Nc3", "Bb4"],
        "defining_move": "3... Bb4",
        "purpose": "c3 나이트를 핀(Pin)하여 백의 e4 중앙 차지를 원천 차단하고, 필요 시 비숍으로 나이트를 잡아 백에게 더블폰 약점을 강요하는 정밀한 하이퍼모던 오프닝",
        "white_plan": "a3(사미쉬)로 비숍을 잡도록 강제하여 비숍 페어를 얻거나, Qc2(클래시컬)로 더블폰을 방지",
        "black_plan": "c5 또는 d5로 백의 중앙을 분쇄하고, c4/c3 약점 폰을 집요하게 공략",
        "key_ideas": "아론 님조비치가 창시한 이래 100년간 1. d4를 상대로 흑의 가장 완벽한 무기로 군림하는 명작",
    },
    {
        "eco": "D80",
        "name": "Grünfeld Defense",
        "name_ko": "그륀펠트 디펜스",
        "moves": ["d4", "Nf6", "c4", "g6", "Nc3", "d5"],
        "defining_move": "3... d5",
        "purpose": "백에게 cxd5와 e4로 거대한 중앙 폰 센터를 넘겨준 뒤, g7 비숍과 ...c5, ...Nc6, ...Bg4로 백의 d4 센터를 사방에서 집중 포격하여 무너뜨리는 하이퍼모던의 극치",
        "white_plan": "cxd5 Nxd5 4. e4 Nxc3 5. bxc3 Bg7 6. Bc4 c5 7. Ne2로 막강한 폰 센터 유지",
        "black_plan": "c5, Nc6, Bg4, Qa5, Rd8로 백의 d4 기점을 연속 타격하여 폰 센터를 폭파",
        "key_ideas": "가리 카스파로프와 막심 바시에-라그라브(MVL)가 애용하는 초고난도 다이내믹 오프닝",
    },

    {
        "eco": "E01",
        "name": "Catalan Opening",
        "name_ko": "카탈란 오프닝",
        "moves": ["d4", "Nf6", "c4", "e6", "g3"],
        "defining_move": "3. g3 (or 3. g3 d5 4. Bg2)",
        "purpose": "퀸스 갬빗의 중앙 압박과 킹스 인디언의 강력한 g2 피앙케토 비숍을 융합한 블라디미르 크람닉의 절대적 무기",
        "white_plan": "Bg2로 긴 대각선을 지배하고 흑의 dxc4 폰을 회수하며 퀸사이드 및 중앙에서 지속적인 압박 가하기",
        "black_plan": "d5 후 dxc4로 폰을 일시 취하거나, Bb4+ 체크 및 c6로 탄탄한 진형 구성",
        "key_ideas": "현대 엘리트 체스에서 가장 안정적이면서도 백에게 영구적 포지셔널 우위를 제공하는 명작",
    },
    {
        "eco": "E12",
        "name": "Queen's Indian Defense",
        "name_ko": "퀸스 인디언 디펜스",
        "moves": ["d4", "Nf6", "c4", "e6", "Nf3", "b6"],
        "defining_move": "3... b6",
        "purpose": "백이 3. Nf3로 님조-인디언(3. Nc3)을 회피할 때, ...b6 후 Bb7 피앙케토로 e4 칸을 통제하려는 극도로 유연하고 견고한 오프닝",
        "white_plan": "4. g3(피앙케토)로 맞불을 놓거나 4. a3(페트로시안 시스템)로 흑 비숍의 침투 차단",
        "black_plan": "Bb7, Be7, O-O, d5 후 c5로 백의 중앙을 차분히 분쇄",
        "key_ideas": "아나톨리 카르포프의 주무기로 알려진 무결점의 하이퍼모던 방어",
    },
    {
        "eco": "E11",
        "name": "Bogo-Indian Defense",
        "name_ko": "보고-인디언 디펜스",
        "moves": ["d4", "Nf6", "c4", "e6", "Nf3", "Bb4+"],
        "defining_move": "3... Bb4+",
        "purpose": "에핌 보고류보프가 창안한 수로, 빠른 체크를 통해 백의 기물 배치를 교란하고 신속한 캐슬링을 준비하는 실전형 오프닝",
        "white_plan": "4. Bd2 또는 4. Nbd2로 체크를 막고 템포를 살려 중앙 폰 센터 구축",
        "black_plan": "4... Qe7 또는 4... Bxd2+ 교환 후 d6, e5로 중앙 카운터",
        "key_ideas": "간결하고 빠른 기물 정리를 통해 복잡성을 줄이는 영리한 수",
    },
    {
        "eco": "A56",
        "name": "Benoni Defense",
        "name_ko": "베노니 디펜스",
        "moves": ["d4", "Nf6", "c4", "c5", "d5"],
        "defining_move": "3. d5",
        "purpose": "백에게 d5 전진 쐐기 폰을 내어주는 대신, 퀸사이드 폰 다수와 g7 피앙케토 비숍으로 폭발적인 다이내믹 반격을 펼치는 오프닝",
        "white_plan": "e4, Bd3, Nf3로 중앙 지배력을 유지하고 킹사이드 돌파(e5 브레이크) 준비",
        "black_plan": "d6, g6, Bg7, O-O 후 ...b5 확장 및 ...Re8로 백의 e4 센터를 정밀 타격",
        "key_ideas": "미하일 탈과 바비 피셔가 불리한 국면을 뒤집을 때 사용한 극적인 카운터 오프닝",
    },
    {
        "eco": "A80",
        "name": "Dutch Defense",
        "name_ko": "더치 디펜스",
        "moves": ["d4", "f5"],
        "defining_move": "1... f5",
        "purpose": "1수부터 f5를 두어 백의 e4 중앙 차지를 과감하게 저지하고, 킹사이드 f-열을 활용해 직접적인 킹사이드 공격을 감행하는 비대칭 오프닝",
        "white_plan": "g3, Bg2, Nf3, O-O 후 d5 또는 e4 중앙 폰 브레이크로 흑의 f-폰 약점 공략",
        "black_plan": "Nf6, e6(클래시컬) 또는 g6(레닌그라드), d6 후 Qe8-Qh5로 백 킹을 향해 전면 공세",
        "key_ideas": "타협 없는 승부를 원하는 공격적인 플레이어들의 비대칭 무기",
    },

    # ==========================================
    # 6. FLANK OPENINGS (1. c4, 1. Nf3, 1. f4, 1. b3)
    # ==========================================
    {
        "eco": "A10",
        "name": "English Opening",
        "name_ko": "잉글리시 오프닝",
        "moves": ["c4"],
        "defining_move": "1. c4",
        "purpose": "중앙 d5 칸을 날개 폰(c4)으로 통제하며, d4/e4를 서두르지 않고 g3-Bg2 피앙케토를 통해 유연하게 판을 짜는 플랭크 오프닝",
        "white_plan": "Nc3, g3, Bg2, d3, Rb1, b4로 퀸사이드 공간을 크게 확장하며 포지셔널 압박",
        "black_plan": "1... e5(리버스 시실리안)로 맞서거나 1... c5(시메트리컬), 1... e6/c6로 유연 대응",
        "key_ideas": "백이 흑의 시실리안 디펜스를 1수 먼저 두는 효과를 누리는 고품격 전략 오프닝",
    },
    {
        "eco": "A04",
        "name": "Réti Opening",
        "name_ko": "레티 오프닝",
        "moves": ["Nf3"],
        "defining_move": "1. Nf3",
        "purpose": "중앙 폰을 올리지 않고 나이트로 d4/e5를 먼저 견제하며 상대의 포메이션을 보고 유연하게 전환(Transposition)하는 만능 수",
        "white_plan": "c4, g3, Bg2, O-O 후 d3 또는 d4로 상대 중앙을 우회 타격",
        "black_plan": "1... d5, 1... Nf6, 1... c5로 중앙을 선점하거나 균형 잡힌 기물 전개",
        "key_ideas": "하이퍼모던의 선구자 리하르트 레티의 철학이 담긴 유연성의 극치",
    },
    {
        "eco": "A02",
        "name": "Bird's Opening",
        "name_ko": "버드 오프닝",
        "moves": ["f4"],
        "defining_move": "1. f4",
        "purpose": "1수부터 e5 칸을 지배하여 흑의 주요 전개를 견제하고, 더치 디펜스를 백 시점으로 구사하여 킹사이드 공격을 노리는 수",
        "white_plan": "Nf3, e3, b3, Bb2 후 Ne5 전초기지를 활용한 킹사이드 공세",
        "black_plan": "1... d5 후 c5, Nc6로 중앙을 장악하거나 1... e5(프롬 갬빗)로 맞불",
        "key_ideas": "전형적인 정석 대결을 피하고 초반부터 난전을 유도하는 개성적인 첫 수",
    },
    {
        "eco": "A01",
        "name": "Nimzo-Larsen Attack",
        "name_ko": "님조-라르센 어택",
        "moves": ["b3"],
        "defining_move": "1. b3",
        "purpose": "Bb2 피앙케토를 통해 e5 중앙 칸과 흑의 킹사이드를 조준하는 벤트 라르센의 하이퍼모던 오프닝",
        "white_plan": "Bb2, e3, f4, Nf3로 긴 대각선 화력을 집중하여 흑 진영을 압박",
        "black_plan": "1... e5 또는 1... d5로 중앙 폰 센터를 선점하고 안정적 기물 전개",
        "key_ideas": "중앙을 점유하지 않고 대각선 기물 화력으로 제어하는 하이퍼모던의 대표작",
    },
]
